name: CI

on:
  push: [main]
  pull_request:
  schedule:
  - cron:  '1 0 * * 0'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build Docker image
      if: "!(startsWith(github.ref, 'refs/tags/'))"
      uses: docker/build-push-action@v1
      with:
        repository: neubauergroup/bluewater-pyhf
        dockerfile: pyhf/Dockerfile
        tags: test
        tag_with_sha: true
        tag_with_ref: true
        push: false
    - name: List Built Images
      run: docker images
    - name: Run test program in Python
      run: >-
        docker run --rm
        neubauergroup/bluewater-pyhf:test
        /bin/bash -c "python3 -m pip list && echo '' && pyhf --version"
