name: Docker Images

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - "pyhf/Dockerfile"
      - ".github/workflows/docker-pyhf.yml"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "pyhf/Dockerfile"
      - ".github/workflows/docker-pyhf.yml"
  schedule:
    - cron:  '1 0 * * 0'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docker:
    name: Build and publish MadGraph images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=neubauergroup/bluewaters-mg5_amc
          VERSION=latest
          MG5_AMC_VERSION=3.1.0
          REPO_NAME=${{github.repository}}
          REPO_NAME_LOWERCASE="${REPO_NAME,,}"
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          TAGS="$TAGS,${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:${MG5_AMC_VERSION},${DOCKER_IMAGE}:sha-${GITHUB_SHA::8}"
          # Releases also have GITHUB_REFs that are tags, so reuse VERSION
          if [ "${{ github.event_name }}" = "release" ]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:latest-stable,ghcr.io/${REPO_NAME_LOWERCASE}:mg5_amc-latest-stable,ghcr.io/${REPO_NAME_LOWERCASE}:mg5_amc-${VERSION}"
          fi
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=repo_name_lowercase::"${REPO_NAME_LOWERCASE}"
          echo ::set-output name=mg5_amc_version::"${MG5_AMC_VERSION}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test build
        id: docker_build_test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: mg5_amc/Dockerfile
          tags: ${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
          load: true
          push: false

      - name: Image digest
        run: echo ${{ steps.docker_build_test.outputs.digest }}

      - name: List built images
        run: docker images

      - name: Test mg5_amc installed
        run: >-
          docker run --rm
          neubauergroup/bluewaters-mg5_amc:sha-${GITHUB_SHA::8}
          /bin/bash -c 'python -m pip list && echo "" && mg5_amc --version'

      - name: Build and publish to registry
        # every PR will trigger a push event on main, so check the push event is actually coming from main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'Neubauer-Group/bluewaters-docker-images'
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: mg5_amc/Dockerfile
          tags: |
            neubauergroup/bluewaters-mg5_amc:latest
            neubauergroup/bluewaters-mg5_amc:${{ steps.prep.outputs.mg5_amc_version }}
            ghcr.io/${{ steps.prep.outputs.repo_name_lowercase }}:mg5_amc-latest
            ghcr.io/${{ steps.prep.outputs.repo_name_lowercase }}:mg5_amc-${{ steps.prep.outputs.mg5_amc_version }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
          push: true

      - name: Build and publish to registry with release tag
        if: github.event_name == 'release' && github.event.action == 'published' && github.repository == 'Neubauer-Group/bluewaters-docker-images'
        id: docker_build_release
        uses: docker/build-push-action@v2
        with:
          context: .
          file: mg5_amc/Dockerfile
          tags: ${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
          push: true
