name: Publish Docker Images

on:
  push:
    # branches:
    # - main
    # tags:
    # - v*

jobs:
  build-and-publish:
    name: Build and publish Docker images to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish to Registry
      if: "!(startsWith(github.ref, 'refs/tags/'))"
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: neubauergroup/bluewaters-pyhf
        dockerfile: pyhf/Dockerfile
        tags: latest,0.6.1
    - name: Build and Publish to Registry with Release Tag
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: neubauergroup/bluewaters-pyhf
        dockerfile: pyhf/Dockerfile
        tags: latest,latest-stable,0.6.1
        tag_with_ref: true
